pfwb_thesaurus/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', 'pfwb_thesaurus.views.home', name='home'),
    url(r'^thesaurus/plone-popup/$', 'pfwb_thesaurus.views.plone_popup'),
    url(r'^thesaurus/term/search/json/$', 'pfwb_thesaurus.views.term_search_json', name='term-search-json'),
    url(r'^thesaurus/term/(?P<pk>\w+)$', 'pfwb_thesaurus.views.term', name='term'),

    url(r'^admin/', include(admin.site.urls)),
)

pfwb_thesaurus/thesaurus/models.py
# pfwb_thesaurus - thesaurus system
# Copyright (C) 2016  Entr'ouvert
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.db import models


class Term(models.Model):
    class Meta:
        ordering = ['term']

    term = models.CharField(max_length=300)
    tabellio_id = models.CharField(max_length=10)

    broader = models.ManyToManyField('self', symmetrical=False,
            related_name='narrower')
    related = models.ManyToManyField('self', symmetrical=True)

    historical_note = models.TextField(blank=True)
    scope_note = models.TextField(blank=True)

    creation_timestamp = models.DateTimeField(auto_now_add=True)
    last_update_timestamp = models.DateTimeField(auto_now=True)


class AlternativeTerm(models.Model):
    primary_term = models.ForeignKey(Term)
    term = models.CharField(max_length=300)

    class Meta:
        ordering = ['term']

pfwb_thesaurus/thesaurus/views.py
from django.shortcuts import render

# Create your views here.

pfwb_thesaurus/views.py
# pfwb_thesaurus - thesaurus system
# Copyright (C) 2016  Entr'ouvert
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import json

from django.conf import settings
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.views.generic import DetailView, ListView

from haystack.query import SearchQuerySet


from .thesaurus.models import Term


class HomeView(ListView):
    model = Term

    def get_queryset(self, qs=None):
        return Term.objects.filter(term__in=settings.HOMEPAGE_START_TERMS)

home = HomeView.as_view()


class PlonePopupView(HomeView):
    template_name = 'thesaurus/plone_popup.html'

plone_popup = PlonePopupView.as_view()


class TermView(DetailView):
    model = Term

term = TermView.as_view()


def term_search_json(request):
    query = request.GET.get('q')
    searchqueryset = SearchQuerySet()
    sqs = searchqueryset.autocomplete(text_auto=query)
    sqs.load_all()

    result = []
    for item in sqs[:15]:
        result.append({'title': item.term, 'url': reverse('term', kwargs={'pk': item.pk}), 'id': item.pk})

    response = HttpResponse(content_type='application/json')
    json.dump({'data': result}, response, indent=2)
    return response

pfwb_thesaurus/templates/base.html
{% extends "gadjo/base.html" %}

pfwb_thesaurus/templates/thesaurus/plone_popup.html
{% extends "thesaurus/term_list.html" %}

{% block aftercontent %}

<script>
function thesaurus_popup_init() {
  $('#term-content a, #thesaurus-terms a, #thesaurus-quick-search a').unbind('click').click(function() {
    $.ajax({
      url: $(this).attr('href'),
      success: function(data, status) {
        $('#thesaurus-quick-search').hide();
        $('#entry-points').hide();
        $('#term-content').empty();
        $(data).find('table').appendTo($('#term-content'));
        $('#term-content').find('button').show().click(function() {
          var orig_link = $('a[rel=#' + $(this).parents('.overlay-ajax').attr('id') + ']');
          var orig_input = $(orig_link).parent().find('input')[0];
          var orig_ac_input = $(orig_link).parent().find('input')[1];
          $(orig_input).val($(orig_input).val() + ' ' + $(this).attr('data-term-id'));
          var labelbox = create_labelbox(
                         orig_ac_input,
                         $(this).attr('data-term-id'),
                          $(this).parent().find('h2').text());
          $(orig_link).before(labelbox);
          $('.close').click();
        });
        thesaurus_popup_init();
        $('#term-content').show();
      }
    });
    return false;
  });
}
$('.pb-ajax').click(function() {
  var $search_result_ul = $('#thesaurus-quick-search ul');
  $search_result_ul.empty().hide();
});
$('#thesaurus-quick-search input').keyup(function() {
  var q = $(this).val();
  var $search_result_ul = $('#thesaurus-quick-search ul');
  $search_result_ul.empty();
  if (q.length == 0) {
    $search_result.hide();
    return;
  }
  $.getJSON($(this).data('autocomplete-json'), {'q': q},
     function(response) {
       $search_result_ul.empty().show();
       $(response.data).each(function(idx, elem) {
         var new_elem = '<li><a href="' + elem.url + '">' + elem.title + '</a></li>';
         $(new_elem).appendTo($search_result_ul);
       });
       thesaurus_popup_init();
     });
});

thesaurus_popup_init();
</script>

{% endblock %}

pfwb_thesaurus/templates/thesaurus/term_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<table>
<tr>
 <td>
 <div>
         <h3>TG (Termes génériques)</h3>
         {% if object.broader.count %}
         <ul>
           {% for term in object.broader.all %}
             <li><a href="{% url 'term' pk=term.pk %}">{{term.term}}</a></li>
           {% endfor %}
         </ul>
         {% else %}
           <i>néant</i>
         {% endif %}
 </div>
 </td>
</tr>
<tr>
 <td><h2>{{object.term}}</h2>
   <button data-term-id="{{object.tabellio_id}}" style="display: none">{% trans 'Select' %}</button>
  {% if object.alternativeterm_set.count %}
  <div>
   <h3>Employé pour (équivalences)</h3>
   <ul>
    {% for alt in object.alternativeterm_set.all %}
      <li>[{{alt.term}}]</li>
    {% endfor %}
   </ul>
  </div>
  {% endif %}
  {% if object.historical_note %}
  <div>
    <p>{{ object.historical_note }}</p>
  </div>
  {% endif %}

 </td>
 <td rowspan="2" valign="top">
  <div>
          <h3>TA (Termes associés — Voir aussi)</h3>
         {% if object.related.count %}
         <ul>
           {% for term in object.related.all %}
             <li><a href="{% url 'term' pk=term.pk %}">{{term.term}}</a></li>
           {% endfor %}
         </ul>
         {% else %}
           <i>néant</i>
         {% endif %}

  </div>
 </td>
</tr>
<tr>
 <td>
  <div>
          <h3>TS (Termes spécifiques)</h3>
         {% if object.narrower.count %}
         <ul>
           {% for term in object.narrower.all %}
             <li><a href="{% url 'term' pk=term.pk %}">{{term.term}}</a></li>
           {% endfor %}
         </ul>
         {% else %}
           <i>néant</i>
         {% endif %}

  </div>
 </td>
</tr>
</table>


{% endblock %}

pfwb_thesaurus/templates/thesaurus/term_list.html
{% extends "base.html" %}

{% block content %}
<div id="thesaurus-quick-search">
<h2>Recherche rapide</h2>
<input type="text" name="thesaurus-quick-search" data-autocomplete-json="{% url 'term-search-json' %}"/>
<div class="thesaurus-search-results"><ul></ul></div>
</div>

<div id="entry-points">
<h2>Points d'entrée</h2>

<ul id="thesaurus-terms">
{% for term in object_list %}
<li><a href="{% url 'term' pk=term.pk %}">{{ term.term }}</a></li>
{% endfor %}
</ul>
</div>

<div id="term-content">
</div>

{% endblock %}